# Generated by Django 4.1.7 on 2023-05-05 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0005_documento_alter_person_id_person_doc"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Documento",
            new_name="Document",
        ),
    ]
