# Generated by Django 4.1.7 on 2023-05-05 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0006_rename_documento_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=7)),
                ("value", models.DecimalField(decimal_places=2, max_digits=5)),
                ("discount", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="clientes.person",
                    ),
                ),
            ],
        ),
    ]
