# Generated by Django 4.1.7 on 2023-05-05 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0007_sale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="clientes.person",
            ),
        ),
    ]
