# Generated by Django 4.1.7 on 2023-05-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0008_alter_sale_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=7)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("product", models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name="sale",
            name="products",
            field=models.ManyToManyField(blank=True, to="clientes.product"),
        ),
    ]
